const menu = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 250,
        img: './images/item-1.jpeg',
        desc: `Not only does buttermilk provide a tangy flavour in pancakes, it helps activate the baking soda and/or baking powder in the batter, making it light and fluffy even before it hits the heat `,
    },
    {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 300,
        img: './images/item-2.jpeg',
        desc: `A huge single or triple burger with all the fixings, cheese, lettuce, tomato, onions and special sauce or mayonnaise! `,
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 150,
        img: './images/item-3.jpeg',
        desc: `Milo blended with banana & mint chocolate chip ice cream, drizzled with melted chocolate & topped with more ice cream & Milo.`,
    },
    {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 250,
        img: './images/item-4.jpeg',
        desc: `In Parsi cuisine, pora is an omelette made from eggs, onion, tomato, green chillies, and coriander leaves.[16] It is usually served for breakfast with Indian/Irani tea and bread `,
    },
    {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 100,
        img: './images/item-5.jpeg',
        desc: ` This is an American Breakfast But here I've made this in Indian style .This will be fun to have omelet & bread in burger style. It's really a headache to think what's the should I give or prepare for breakfast in hurry. `,
    },
    {
        id: 6,
        title: 'oreo dream',
        category: 'shakes',
        price: 150,
        img: './images/item-6.jpeg',
        desc: `A super easy milkshake made with vanilla ice cream, milk, and Oreo cookies!  This sweet treat is a hit with the whole family on a hot day!`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 350,
        img: './images/item-7.jpeg',
        desc: `High-quality meats, cheeses, toppings and condiments will ensure your sandwich looks and tastes its best `,
    },
    {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 200,
        img: './images/item-8.jpeg',
        desc: `Fried chicken, biscuits, chicken and dumplings, chicken-fried steak and gravy, fried green tomatoes, or shrimp and grits, these dishes are popular. `,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'shakes',
        price: 200,
        img: './images/item-9.jpeg',
        desc: `Book a table for 2 in open top hall as per quarantine guidelines`,
    },
];
export default menu;
